apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.backend.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.app.backend.name }}-service
spec:
  type: ClusterIP
  selector:
    name: {{ .Values.app.backend.name }}
  ports:
    - name: api-http
      protocol: TCP
      port: 8181
      targetPort: 8181


