apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # References:
  # * https://github.com/argoproj/argo-workflows/blob/v3.1.6/config/config.go
  # * https://github.com/argoproj/argo-workflows/blob/v3.1.6/docs/workflow-controller-configmap.md
  # * https://github.com/argoproj/argo-workflows/blob/v3.1.6/docs/workflow-controller-configmap.yaml

  # Emissary Executor: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary
  containerRuntimeExecutor: emissary
  workflowDefaults: |
    metadata:
      annotations:
        argo: workflows
      labels:
        foo: bar
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 8737
        runAsGroup: 8737
        runAsUser: 8737