apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
  namespace: trino
  labels:
    app: { { template "trino.name" . } }
    chart: { { template "trino.chart" . } }
    release: { { .Release.Name } }
    heritage: { { .Release.Service } }
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: hivemeta
        image:  {{ .Values.hivemetastore.image }}
        command: ["/opt/hive-metastore/bin/schematool"]
        args: ["--verbose" ,"-initSchema" , "-dbType", "postgres" , "-userName", "{{ .Values.hivemetastore.postgres.user }}", "-passWord", "{{ .Values.hivemetastore.postgres.password }}" , "-url", "jdbc:postgresql://{{ .Values.hivemetastore.postgres.host }}/{{ .Values.hivemetastore.postgres.db }}"]
      restartPolicy: Never
  backoffLimit: 1