---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector: {}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: traefikv2
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress
        ports:
         - protocol: TCP
           port: {{ .Values.containerPort }}       
  policyTypes:
  - Ingress
