# LICENSE START
# 
# MIT License
# 
# Copyright (c) 2019 Daimler TSS GmbH
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
# LICENSE END 
#
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : Lov.yaml
#  **
#  ** Module     : core
#  ** 
#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
swagger: "2.0"
info:
 version: "1.0.0"
 title: "Lov Maintenance Service"
host: "localhost:7175"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "lov"
   description: "This service is used to maintain LOV used in storage service."

schemes:
- "https"

paths:

# path to getAll valid configured Classification types
#
#  supprorted http methods GET 
#
# path example ../classifications

 /classifications:
  get:
   tags:
    - "lov"
   summary: "Get all classification types."
   description:  "Get all classification types. This endpoints will be used to Get all valid available classification types."
   operationId: "getAllclassificationType"
   parameters:
     - name: orderBy
       in: query
       description: Sort classification types by a given order like ascending(asc) or descending(desc)
       required: false
       type: string
       enum: [asc, desc]
   responses:
    201:
     description: "Returns message of succes or failure"
     schema:
       $ref: "#/definitions/ClassificationVOCollection"
    204:
      description: "Fetch complete, no content found."
    400:
     description: "Bad request."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Method not allowed"
    500:
     description: "Internal error"

definitions:
 ClassificationVO:
  type: object
  properties: 
    id:
     type: string
     description: "ID of Business Goal"
    name:
     type: string
     description: "Name of the Business Goal"
     minLength: 1
     
 ClassificationVOCollection: 
  description: "Collection of classification types."
  type: object
  properties:
   data:
    type: array
    items: 
     $ref: "#/definitions/ClassificationVO" 
       

 BindingResult:
  type: object
 
 GenericMessage:
  type: object
  properties:
    success:
      type: string
    errors:
      type: array
      items: 
        $ref: "#/definitions/MessageDescription"
  
 MessageDescription:
  type: object
  properties:
    message: 
      type: string
      description: "error message"
      