{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notebooks-ingress
  namespace: {{ .Values.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: proxy-public
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: notebook-tls         
{{- end }}
