---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role-kale-ns
  namespace: $(profile-name)
rules:
- apiGroups: ["argoproj.io"]
  resources: ["pods", "workflows"]
  verbs: ["get", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: kale-ns
  namespace: $(profile-name)
subjects:
- kind: ServiceAccount
  name: default-editor

roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: workflow-role-kale-ns # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
