apiVersion: v1
kind: Secret
metadata:
  name: offical-airflow-client-secret
  namespace: airflow
  labels:
    tier: airflow
    component: config
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  
type: Opaque
data:
  offical-airflow-client-secret.json: {{ .Values.clientSecret }}
