apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfserving-models-web-app
  namespace: kfserving-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kfserving-models-web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kfserving-models-web-app
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534    
      containers:
      - image: dna/kfserving/models-web-app:v0.7.0
        imagePullPolicy: Always
        name: kfserving-models-web-app
        envFrom:
          - configMapRef:
              name: kfserving-models-web-app-config
        ports:
        - containerPort: 5000
      serviceAccountName: kfserving-models-web-app
