apiVersion: v2
appVersion: 0.4.0
description: A chart for unseal Vault cron job
keywords:
- vault
- unseal
- cron
name: vault-auto-unseal
sources:
- https://github.com/mercedes-benz/DnA.git
type: application
version: 0.4.0
