version: "2.1"
services:
  storage-mfe:
    image: ${STORAGE_MFE:-storage_mfe}
    build:
      context: ../../../packages/storage-mfe/
      dockerfile: $PWD/storage-mfe.Dockerfile
    environment:
      - PROJECTSMO_CONTAINER_APP_URL=""
      - PROJECTSMO_FRONTEND_API_BASEURL=""
    ports:
      - 9000:3000
