apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow-git-sync.secret" . }}
  namespace: {{ .Values.namespace }}
data:
  #gitSshKey: {{ .Values.secret.gitSshKey | quote }}
  #ssh: {{ .Values.secret.gitSshKey | quote }}
  #known_hosts: {{ .Values.secret.knownHosts | quote }}
  GIT_SYNC_USERNAME: {{ .Values.secret.gitUserName | quote }}
  GIT_SYNC_PASSWORD: {{ .Values.secret.gitPassword | quote }}

