spring:
  application:
    name: daimler-mbc-dna-malware-scanner
    
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:11MB}
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  port: 8181
  servlet:
    context-path: /avscan

clamavservice:
  uploadDir: /tmp
  clamAvHost: ${CLAMAV_BACKEND_URL:localhost}
  clamAvPort: ${CLAMAV_BACKEND_PORT:3310}


malware:
    api:
      security:
         uri: ${AUTH_API_HOST:http://localhost:7171/api/subscription/validate}
         token: ${AUTH_API_TOKEN:XXXXX}
    basicAuth: 
      token: ${ONEAPI_BASICAUTH_TOKEN:XXXXX}
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: ${RESTRICTED_URL_PATTERN:/avscan/api/v1/scan.*}
    http-response-body: "{ \"success\": \"Too Many Requests\", \"errors\": [{ \"message\": \"You have exhausted your API Request Quota\" }],\"warnings\": null}"
    strategy: first
    rate-limits:
    - expression:  "getHeader('appId')"
      bandwidths:
      - capacity: ${API_REQUEST_LIMIT:1}
        time: ${WITH_IN:20}
        unit: ${TIME_UNIT:seconds}     
        
management.endpoints.web.exposure.include: loggers,health
management.endpoint.loggers.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always

logging:
  service:
    environment: ${LOGGING_ENVIRONMENT:DEV}
    path: ${LOGGING_PATH:/logs}
  level:
    com:
      daimler:
        mbc:
          dna:
            malwarescanner: INFO
    org.springframework.boot.autoconfigure.logging: INFO
