micronaut:
  application:
    name: dataiku
  http:
    client:
      ssl:
        insecureTrustAllCertificates: true  
  server:
    port: 7777
    cors: 
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://*
          allowedMethods:
            - POST
            - PUT
            - GET
            - PATCH
            - OPTIONS
            - HEAD
            - DELETE

dna:
  uri: ${DNA_URI:XXXX}
  dnaAuthEnable: ${DNA_AUTH_ENABLE:false}
  verifyLoginUri: ${DNA_VERIFYLOGIN_URI:XXXX}
  getUsersUri: ${DNA_GETUSERS_URI:XXXX}
  jwt: ${JWT_SECRET_KEY:XXXXX}
