apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Chart.Name }}-service
spec:
  type: ClusterIP
  selector:
    name: {{ .Chart.Name }}
  ports:
    - name: api
      protocol: TCP
      port: 3310
      targetPort: 3310
      
