# LICENSE START
# 
# MIT License
# 
# Copyright (c) 2019 Daimler TSS GmbH
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
# LICENSE END 
# 
#-----------------------------------------------------------------------------------------------------
#  **
#  ** File Name  : carlafunction.yaml
#  **
#  ** Module     : core
#  ** 

#  -------------------------------------------------------------------------------------------------------
#
#  CHANGE HISTORY
#
#  Created By         :  BEALURI
#
#  Bug Number         :  
#  Changed By         :  
#  Change Description :  
#  Change On          :  
#  Search String      :  
#  
#  -------------------------------------------------------------------------------------------------------
  

swagger: "2.0"
info:
 version: "1.0.0"
 title: "core carlafunction Service"
host: "localhost:7184"
basePath: "/api/1.0"
consumes:
 - "application/json"
produces:
 - "application/json"
tags:
 - name: "carlafunctions"
   description: "This service is used to maintain carlafunction used in dataproducts."

schemes:
- "https"

paths:

# path to fetch all valid carlafunctions or by intent
#
#  supprorted http methods GET, POST and DELETE 
#
# path example ../carlafunctions

 /carlafunctions:
  
  get:
   tags:
    - "carlafunctions"
   summary: "Get all available carlafunctions."
   description:  "Get all carlafunctions. This endpoints will be used to Get all valid available carlafunctions maintenance records."
   operationId: "getAll"
   parameters:
        - name: sortBy
          in: query
          description: Sort carlafunctions by a given variable like name
          required: false
          type: string
          enum: [name]
        - name: sortOrder
          in: query
          description: Sort carlafunctions based on the given order, example asc,desc
          required: false
          type: string   
          enum: [asc,desc]
        - name: offset
          in: query
          description: page number from which listing of carlafunctions should start. Offset. Example 2
          required: false
          type: integer  
        - name: limit
          in: query
          description: size to limit the number of carlafunctions, Example 10
          required: false
          type: integer
      
   responses:
    201:
     description: "Returns message of succes or failure"
     schema:
       $ref: "#/definitions/CarlafunctionCollection"
    204:
      description: "Fetch complete, no content found."
    400:
     description: "Bad request."
    401:
     description: "Request does not have sufficient credentials."
    403:
     description: "Request is not authorized."
    405:
     description: "Method not allowed"
    500:
     description: "Internal error"

# path to get existing carlafunctions
#
#  supported http methods GET
#
# path examples----


 /carlafunctions/{id}:
  get:
    tags:
    - "carlafunctions"
    summary: "get the carlafunctions  by given ID."
    description:  "get the carlafunctions  by given ID"
    operationId: "getByID"
    parameters:
      - name: "id"
        in: "path"
        description: "Id of the carlafunction"
        required: true
        type: "string"
    responses:
      200:
          description: "Returns message of success or failure"
          schema:
            $ref: "#/definitions/CarlaFunctionVO"
      400:
       description: "Bad request"
      401:
       description: "Request does not have sufficient credentials."
      403:
       description: "Request is not authorized."
      404:
       description: "Invalid id, record not found."
      500:
       description: "Internal error"
     
definitions:
 CarlaFunctionVO:
    type: object
    properties:  
      id:
        type: string
      name:
        type: string
        
 CarlafunctionCollection: 
  description: "Collection of Carlafunctions."
  type: object
  properties: 
    data: 
      type: array
      items: 
        $ref: "#/definitions/CarlaFunctionVO"
    totalCount:
      type: integer
      description: "Total records from the database"
 