apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "konga.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  userdb.data: |
    {{ .Values.userdb_data | nindent 8 }} 
  kong_node.data: |
    {{ .Values.kong_node_data | nindent 8 }}