apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "data-product-mfe.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  # ingress:
  #   - ports:
  #       - port: {{ .Values.containerPort }}
  ingress:
    - from:
      - podSelector:
         matchLabels:
           app.kubernetes.io/name: traefikv2
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress
        ports:
         - protocol: TCP
           port: {{ .Values.containerPort }}    
  podSelector:
    matchLabels:
      {{- include "data-product-mfe.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
