apiVersion: v1
kind: Service
metadata:
  name: proxy-api
  namespace: {{ .Values.namespace }}
  labels:
    component: proxy
spec:
  selector:
    component: proxy
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-public
  namespace: {{ .Values.namespace }}
  # annotations:
  #   loadbalancer.openstack.org/keep-floatingip: "false"
  # finalizers:
  #   - service.kubernetes.io/load-balancer-cleanup
  labels:
    component: proxy
spec:
  selector:
    component: proxy
  ports:
    - name: https
      port: 443
      protocol: TCP
    - name: http
      port: 8000
      protocol: TCP
      #targetPort: 80
      targetPort: 8000
  type: NodePort    
  #type: LoadBalancer
  #loadBalancerIP: 53.6.44.202
