# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: dna
namespace: dna
imagePullSecret: 
  name: harbor-pull-secret
  key: "" 
cert:
  certManager: acme
replicaCount: 1

traefik:
  image: ""

ingress:
  namespace: ingress
  host: ""
  lbIP: ""

app:
  backend:
    replicaCount: 1
    image: backend:latest
    secrets: 
      name: app-secrets
      notebookSecretToken: ""
      oidcClientID: ""
      oidcClientSecret: ""
      drdCertPassword: ""
      jwtSecretKey: ""
      s3AccessKey: ""
      s3SecretKey: ""
      dataikuProdApiKey: ""
      dataikuTrainingApiKey: ""
      avscanApiKey: ""
      appDBUserName: ""
      appDBPassword: ""
    config:
      enableItsmm: false
      enableJupyterNotebook: false
      enableDataiku: false
      enableAttachmentScan: false
      enableInternalUser: false
      redirectUrl: ""
      dbUri: jdbc:postgresql://postgresql:64000/db
      oidcUserInfoUrl: ""
      oidcTokenIntrospectionUrl: ""
      oidcProvider: INTERNAL
      oidcTokenRevocationUrl: ""
      internalUserRequestUrl: ""
      internalCertFile: ""
      oidcDisabled: true
      s3BucketName: ""
      s3Url: ""
      corosOriginUrl: ""
      jupyterNotebookUrl: ""
      vaultHost: vault.vault.svc.cluster.local
      vaultPort: 8200
      dataikuProdUri: ""
      dataikuProdAdminGroup: ""
      dataikutraininguri: ""
      avscanAppId: ""
      naasBroker: broker01.kafka.svc.cluster.local:8001
      loggingEnvironment: dev
      loggingPath: /tmp/app/log
      dataikuProjectUri: /projects/
      dataikuTrainingAdminGroup: ""
      avscanUri: ""
      flywayBaseline: ""
      flywayBaselineOnMigrate: ""
      flywayBaselineVersion: ""
      flywaySchema: ""

  frontend:
    replicaCount: 1
    image: frontend
    config: 
      oidcDisabled: true
      oidcProvider: INTERNAL
      apiBaseUrl: api
      jupyterNotebookUrl: ""
      jupyterNotebookOidcPopUpUrl: ""
      dataikuLiveAppUrl: ""
      dataikuTrainingAppUrl: ""
      oauth2TokenUrl: ""
      oauth2AuthUrl: ""
      oauth2RevokeUrl: ""
      oauth2LogoutUrl: ""
      oauth2IntrospectionUrl: ""
      oauth2UserInfoUrl: ""
      frontendClientid: ""
      redirectUrls: ""
      swaggerUiUrl: ""
      dataikuFerretUrl: ""
      mlPipelineUrl: ""
      appNameHeader: ""
      appNameHome: ""
      contactUsHtml: <div><p>There could be many places where you may need our help, and we are happy to support you. <br /> Please add your communication channels links here</p></div>
      brandLogoUrl: /images/branding/logo-brand.png
      appLogoUrl: /images/branding/logo-app.png
      enableInternalUserInfo: true
      enableDataCompliance: true
      enabledReports: false
      enableJupyterWorkspace: false
      enableDataikuWorkspace: false
      enableMalwareService: false
      enableDataPipelineService: false
      enablePipelineService: false
      enabledMlPipelineService: false
      enableMalwareApiInfo: false
      enableNotification: false
      companyName: XYZ
      
  ngnix:
    jupyServer: http://proxy-public:8000
    grafanaServer: http://i3-monitoring-grafana.i3-monitoring.svc.cluster.local:80
    avscanServer: http://clamav-rest-service.clamav.svc.cluster.local:8181
    avscanMgwServer: http://microgateway.clamav.svc.cluster.local:80
    airflowServer: http://airflow.airflow.svc.cluster.local:8080
    naasServer: http://naas-backend-service.naas.svc.cluster.local:7272
    dashboard: http://dashboard-backend-service.dashboard.svc.cluster.local:7173
   
  vault:
    secret:
      name: vault-secrets
      rootToken: ""