apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: api-http
      port: 80
      protocol: TCP
      targetPort: 7171
  selector:
    app: {{ .Values.appName }}backend