apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-ingress-route
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)
    #- match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: 80
      middlewares:
        - name: https-redirect
          #namespace: ingress