version: "2.1"
services:
  dataProduct-mfe:
    image: ${IMAGE_DATA_PRODUCT_MFE:-dataProduct-mfe}
    container_name: data-product-mfe
    build:
      context: ../../../packages/data-product-mfe/
      dockerfile: $PWD/dataProduct-mfe.Dockerfile
  
  dataProduct-be:
    image: ${IMAGE_DATA_PRODUCT_BE:-dataProduct_be}
    build:
      context: ../../../packages/data-product-backend/
      dockerfile: $PWD/dataProduct-be.Dockerfile
