apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-web-allow-netpol
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Chart.Name }}-backend
  ingress:
    - from:
       - podSelector:
          matchLabels:
            app: dna-kong-gw-kong
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kong      
    # - from:
    #   - podSelector: 
    #       matchLabels:
    #         component: jupyter
    - ports:
      - port: 7272
    #   from: []
  #   - ports:
  #     - port: 8080
  #       protocol: TCP
  policyTypes:
  - Ingress

