apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.db.secrets.name}}
  namespace: {{ .Values.namespace}}
type: Opaque
data:
  postgres.backupuser.username : {{ .Values.app.db.secrets.backupUserName | b64enc | quote }}
  postgres.backupuser.password : {{ .Values.app.db.secrets.backupUserPassword | b64enc | quote }}
  postgres.dbadm.username : {{ .Values.app.db.secrets.dbAdminUserName | b64enc | quote }}
  postgres.dbadm.password : {{ .Values.app.db.secrets.dbAdminPassword | b64enc | quote }}
  postgres.patroniuser.password : {{ .Values.app.db.secrets.patroniUserPassword | b64enc | quote }}
  postgres.app.username: {{ .Values.app.db.secrets.appUserName | b64enc | quote }}
  postgres.app.password: {{ .Values.app.db.secrets.appPassword | b64enc | quote }}