version: "2.1"
services:
  result-notebook:
    image: ${IMAGE_RESULT_NOTEBOOK:-pyspark-custom-notebook}
    build:
      context: ./dockerfiles/notebooks
      dockerfile: $PWD/dockerfiles/notebooks/singleuser-notebook-base.Dockerfile
      # args:
      #   http_proxy: "$HTTP_PROXY"
      #   https_proxy: "$HTTPS_PROXY"
      #   no_proxy: "$NO_PROXY"
  
  result-configurable-httpproxy:
    image: ${IMAGE_RESULT_CONFIGPROXY:-configurable-http-proxy}
    build:
      context: ./dockerfiles/notebooks
      dockerfile: $PWD/dockerfiles/notebooks/configurableHttpProxy.Dockerfile
      # args:
      #   http_proxy: "$HTTP_PROXY"
      #   https_proxy: "$HTTPS_PROXY"
      #   no_proxy: "$NO_PROXY"   

  result-hub:
    image: ${IMAGE_RESULT_HUB:-jupyterhub}
    build:
      context: ./dockerfiles/notebooks
      dockerfile: $PWD/dockerfiles/notebooks/jupyterhub.Dockerfile
      # args:
      #   http_proxy: "$HTTP_PROXY"
      #   https_proxy: "$HTTPS_PROXY"
      #   no_proxy: "$NO_PROXY"
  
