version: "3.5"
services:
  pyspark-notebook-base:
    image: pyspark-notebook-base:latest
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/singleuser-notebook-base.Dockerfile

  pyspark-notebook-default:
    image: ${IMAGE_DEFAULT_NOTEBOOK:-pyspark-notebook-default}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/singleuser-notebook-default.Dockerfile
    depends_on:
      - pyspark-notebook-base
   
  pyspark-notebook-tensorflow:
    image: ${IMAGE_TENSORFLOW_NOTEBOOK:-pyspark-notebook-tensorflow}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/singleuser-notebook-tensorflow.Dockerfile
      args:
        defaultimage: ${IMAGE_DEFAULT_NOTEBOOK:-pyspark-notebook-default}
    depends_on:
      - pyspark-notebook-default
  
  result-configurable-httpproxy:
    image: ${IMAGE_RESULT_CONFIGPROXY:-configurable-http-proxy}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/configurableHttpProxy.Dockerfile

  result-hub:
    image: ${IMAGE_RESULT_HUB:-jupyterhub}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/jupyterhub.Dockerfile
  
