version: "3.5"
services:
  pyspark-notebook-base:
    image: vardhandevalla/pyspark-notebook-base:vokta.dev
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/singleuser-notebook-base.Dockerfile

  pyspark-notebook-default:
    image: ${IMAGE_DEFAULT_NOTEBOOK:-vardhandevalla/pyspark-notebook-default:vokta.dev}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/singleuser-notebook-default.Dockerfile
    depends_on:
      - pyspark-notebook-base
   
  pyspark-notebook-tensorflow:
    image: ${IMAGE_TENSORFLOW_NOTEBOOK:-vardhandevalla/pyspark-notebook-tensorflow:vokta.dev}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/singleuser-notebook-tensorflow.Dockerfile
      args:
        defaultimage: ${IMAGE_DEFAULT_NOTEBOOK:-vardhandevalla/pyspark-notebook-default:vokta.dev}
    depends_on:
      - pyspark-notebook-default
  
  result-configurable-httpproxy:
    image: ${IMAGE_RESULT_CONFIGPROXY:-vardhandevalla/configurable-http-proxy:vokta.dev}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/configurableHttpProxy.Dockerfile

  result-hub:
    image: ${IMAGE_RESULT_HUB:-vardhandevalla/jupyterhub:vokta.dev}
    build:
      context: ./dockerfiles/notebooks/${FOLDER_PATH:-}
      dockerfile: $PWD/dockerfiles/notebooks/${FOLDER_PATH:-}/jupyterhub.Dockerfile
  
