kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-backup
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-retain
