apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matomo-be.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingress:
    - ports:
        - port: {{ .Values.containerPort }}
  podSelector:
    matchLabels:
      {{- include "matomo-be.selectorLabels" . | nindent 8 }}
