apiVersion: v1
kind: Service
metadata:
  name: {{ include "matomo-be.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "matomo-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "matomo-be.selectorLabels" . | nindent 4 }}
