varReference:
- path: spec/owner/name
  kind: Profile
- path: metadata/name
  kind: Profile
- path: metadata/namespace
  kind: AuthorizationPolicy
  name: allowlist-by-paths
- path: spec/rules/when/values
  kind: AuthorizationPolicy
  name: allowlist-by-paths
- path: metadata/namespace
  kind: PodDefault
- path: metadata/namespace
  kind: EnvoyFilter
- path: spec/configPatches/patch/value/request_headers_to_add/header/value
  kind: EnvoyFilter
- path: metadata/namespace
  kind: Role
- path: metadata/namespace
  kind: RoleBinding
- path: spec/rules/from/source/principals
  kind: AuthorizationPolicy
- path: metadata/name
  kind: AuthorizationPolicy  
- path: metadata/namespace
  kind: AuthorizationPolicy
  name: notebooks-authorization
- path: spec/rules/when/values
  kind: AuthorizationPolicy
  name: notebooks-authorization
- path: metadata/namespace
  kind: NetworkPolicy
  name: allow-all
- path: metadata/namespace
  kind: Secret
  name: s3creds
- path: metadata/namespace
  kind: ServiceAccount
  name: minio-models   