apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow-git-sync-known-hosts.configmap" . }}
  namespace: {{ .Values.namespace }}
data:
  known_hosts: {{ .Values.secret.knownHosts | b64dec | quote }}
