apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "airflow.name" . }}-weballow-netpol
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      name: {{ include "airflow-service.name" . }}
  ingress:
    - from:
      - podSelector: 
          matchLabels:
              name: {{ include "airflow-service.name" . }}      
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: traefikv2
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress         
    - ports:
      - port: {{ .Values.service.port }}
  policyTypes:
    - Ingress    
