apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-pull.secret.name" . }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecretData }}
