apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.secret" . }}
  namespace: {{ .Values.namespace }}
data:
  # postgresql+psycopg2://root:root@postgres-airflow:5432/airflow
  SQL_ALCHEMY_CONN: {{ .Values.secret.postgresql.sqlAlchemyConn | b64enc }}
