apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow-git-sync.secret" . }}
  namespace: {{ .Values.namespace }}
data:
  GIT_SYNC_USERNAME: {{ .Values.secret.gitUserName | b64enc | quote }}
  GIT_SYNC_PASSWORD: {{ .Values.secret.gitPassword | b64enc | quote }}