apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow-service.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
  selector:
    name: {{ include "airflow-service.name" . }}
