apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow-service-account.name" . }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "airflow-service-role.name" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airflow-service-role.name" . }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "airflow-service-account.name" . }}
roleRef:
  kind: Role
  name: {{ include "airflow-service-role.name" . }}
  apiGroup: rbac.authorization.k8s.io
