spring:
  application:
    name: dna-storage-service
    version: 3.2.4
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:53.137.138.233}
    port: ${REDIS_PORT:6379}
    user: ${REDIS_ROOT_USER:default}
    password: ${REDIS_ROOT_PASSWORD:PGn3W4yfNZ}
    
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baselineVersion: ${FLYWAY_BASELINEVERSION:0}
    schemas: ${FLYWAY_SCHEMA:public}      
    
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

  datasource:
    hikari:
      connection-timeout: 4000
    platform: postgres
    url: ${API_DB_URL:jdbc:postgresql://53.137.140.156:64000/storage}
    username: ${API_DB_USER:storage}
    password: ${API_DB_PASS:abcf02d283e9be06ea55ba189a2a00a77d35d12a}
    driverClassName: org.postgresql.Driver
       
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:3000MB}
      max-request-size: ${MAX_REQUEST_SIZE:3000MB}
    
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${NAAS_BROKER:53.137.140.156:8001}
    vault:
      host: ${VAULT_HOST:serving.kfp.***REMOVED***}
      port: ${VAULT_PORT:443}
      scheme: ${VAULT_SCHEME:https}
      authentication: ${VAULT_AUTHENTICATION:TOKEN}
      token: ${VAULT_TOKEN:***REMOVED***}
      mountpath: ${VAULT_MOUNTPATH:kv}
      vaultpath: ${VAULT_PATH:dna/minio}
      kv:
       enabled: true  

kafka:
  centralTopic:
    name: dnaCentralEventTopic      
dna:
  uri: ${DNA_URI:http://dna-app-backend-service.dna.svc.cluster.local:80}
  dnaAuthEnable: ${DNA_AUTH_ENABLE:false}
  feature:
     attachmentMalwareScan: ${ATTACHMENT_MALWARE_SCAN:false}
  malwareScan:
     appId: ${MALWARE_SCANNER_APP_ID:xxxxx}
     apiKey: ${MALWARE_SCANNER_API_KEY:xxxxx}
     uri: ${MALWARE_SCANNER_URI:XXXXXX}
      
jwt:
  secret:
    key: ${JWT_SECRET_KEY:oeRaYY7Wo24sDqKSX3IM9ASGmdGPmkTd9jo1QTy4b7P9Ze5_9hKolVX8xNrQDcNRfVEdTZNOuOyqEGhXEbdJI-ZQ19k_o9MI0y3eZN2lp9jow55FfXMiINEdt1XR85VipRLSOkT6kSpzs2x-jbLDiz9iFVzkd81YKxMgPA7VfZeQUm4n-mOmnWMaVX30zGFU4L3oPBctYKkl4dYfqYWqRNfrgPJVi5DGFjywgxx0ASEiJHtV72paI3fDR2XwlSkyhhmY-ICjCRmsJN4fX1pdoL8a18-aQrvyu4j0Os6dVPYIoPvvY0SAZtWYKHfM15g7A3HD4cVREf9cUsprCRK93w}
server:
  port: 7175

#Cors Filter origin Domains  
allowedCorsOriginPatternUrl: ${CORS_ORIGIN_URL:http://*}

storage:
  termsOfUse.uri: ${STORAGE_TERMS_OF_USE_URL:https://***REMOVED***/docs/DOC-467646}
  connect.host: ${STORAGE_CONNECT_HOST:***REMOVED***}
  httpMethod: ${HTTP_METHOD:https://}
  mc.commandkeyword: ${MC_CMD_KEY:sh}
  mc.timeout.alias: ${MC_ALIAS_TIMEOUT:10}
  mc.timeout.listpolicies: ${MC_LISTPOLICIES_TIMEOUT:10}
      
 
minio:
  clientApi: ${MINIO_CLIENT_API:http://53.137.143.78:9000}
  endpoint: ${MINIO_ENDPOINT:http://53.137.143.78:9000}
  accessKey: ${MINIO_ROOT_USER:admin} 
  secretKey: ${MINIO_ROOT_PASSWORD:Ql1aqWvUXg}
  version: ${MINIO_POLICY_VERSION:2012-10-17}

databricks:
  userid: ${DATABRICKS_USERID:XXXXX}
  userauth: ${DATABRICKS_USER_AUTH:XXXXX}
  
# For dataiku connection  
dataiku:
  connectionsUriPath: ${DATAIKU_CONNECTION_URI_PATH:/admin/connections}
  projectsUriPath: ${DATAIKU_PROJECTS_URI_PATH:/projects/}
  projectPermissionUriPath: ${DATAIKU_PERMISSION_URI_PATH:/permissions}
  production:
    uri: ${DATAIKU_PROD_URI:XXXXXX}
    apiKey: ${DATAIKU_PROD_API_KEY:XXXXXX}
  training:
    uri: ${DATAIKU_TRAINING_URI:XXXXXX}
    apiKey: ${DATAIKU_TRAINING_API_KEY:XXXXXX}  

swagger.headers.authorization.token: ${SWAGGER_HEADER_AUTH:XXXXXX}
management.endpoints.web.exposure.include: loggers,health
management.endpoint.loggers.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always

logging:
  service:
    environment: ${LOGGING_ENVIRONMENT:DEV}
    path: ${LOGGING_PATH:/home/coder/app/packages/storage-backend/}
  level:
    com:
      daimler:
        data:
          application: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO
