spring:
  application:
    name: dna-storage-service
    
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

  datasource:
    hikari:
      connection-timeout: 4000
    platform: postgres
    url: ${API_DB_URL:jdbc:postgresql://localhost:5432/db}
    username: ${API_DB_USER:XXXX_user}
    password: ${API_DB_PASS:XXXX_pass}
    driverClassName: org.postgresql.Driver
       
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:3000MB}
      max-request-size: ${MAX_REQUEST_SIZE:3000MB}
    
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${NAAS_BROKER:localhost:9092}
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      authentication: ${VAULT_AUTHENTICATION:TOKEN}
      token: ${VAULT_TOKEN:***REMOVED***}
      mountpath: ${VAULT_MOUNTPATH:secret}
      vaultpath: ${VAULT_PATH:dna}
      kv:
       enabled: true  

kafka:
  centralTopic:
    name: dnaCentralEventTopic      
dna:
  uri: ${DNA_URI:XXXXXX}
  dnaAuthEnable: ${DNA_AUTH_ENABLE:false}
  feature:
     attachmentMalwareScan: ${ATTACHMENT_MALWARE_SCAN:false}
  malwareScan:
     appId: ${MALWARE_SCANNER_APP_ID:xxxxx}
     apiKey: ${MALWARE_SCANNER_API_KEY:xxxxx}
     uri: ${MALWARE_SCANNER_URI:XXXXXX}
      
jwt:
  secret:
    key: ${JWT_SECRET_KEY:XXXXXX}
server:
  port: 7175
  servlet:
    context-path: /storage

#Cors Filter origin Domains  
allowedCorsOriginPatternUrl: ${CORS_ORIGIN_URL:http://*}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ADMIN_ACCESS_KEY:XXXXXX} 
  secretKey: ${MINIO_ADMIN_SECRET_KEY:XXXXXX}
  version: ${MINIO_POLICY_VERSION:2012-10-17}

swagger.headers.authorization.token: ${SWAGGER_HEADER_AUTH:XXXXXX}
management.endpoints.web.exposure.include: loggers,health
management.endpoint.loggers.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always

logging:
  service:
    environment: ${LOGGING_ENVIRONMENT:DEV}
    path: ${LOGGING_PATH:/var/log}
  level:
    com:
      daimler:
        data:
          application: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO