apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage-mfe.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "storage-mfe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "storage-mfe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "storage-mfe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "storage-mfe.fullname" . }}
          configMap:
            name: {{ include "storage-mfe.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5                
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5            
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "storage-mfe.fullname" . }}
              mountPath: /opt/bitnami/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: {{ include "storage-mfe.fullname" . }}
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json                
