apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.backend.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  onapi.basicauth.token: {{ .Values.app.backend.secrets.onapibasicauthtoken | quote }}