apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
    zone: web
    
spec:
  replicas: {{ .Values.appFrontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        zone: web
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - image: {{ .Values.appFrontend.image }}
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            exec:
              command:
                - /bin/bash
                - -c
                - "[ -f /opt/bitnami/nginx/tmp/nginx.pid ]"
              
          readinessProbe:
            # initialDelaySeconds: 30
            # Max time it will take to success the readiness probe .
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            httpGet:
              path: {{ .Values.probes.readinessProbe.path }}
              port: {{ .Values.probes.readinessProbe.port }}  
          volumeMounts:
            - name: {{ .Release.Name }}-frontend-configmap-ngnix
              mountPath: /opt/bitnami/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: {{ .Release.Name }}-frontend-configmap-configjs
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js                 
          resources: {}
      securityContext:
        runAsUser: 1001
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      volumes:
        - name: {{ .Release.Name }}-frontend-configmap-ngnix
          configMap:
            name: {{ .Release.Name }}-frontend-configmap        
        - name: {{ .Release.Name }}-frontend-configmap-configjs
          configMap:
            name: {{ .Release.Name }}-frontend-configmap                     