# To allow acme cert resolver pod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-acme-http01-solver
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: 'true'  
  ingress:
    - ports:
        - protocol: TCP
          port: 8089
    - from:
        - podSelector:
            matchLabels:
              app: traefik
          namespaceSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - ingress
  policyTypes:
    - Ingress
---
# To allow minio api, console, operator traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.tenant.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: minio
  ingress:
    - ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9090                            
  policyTypes:
    - Ingress