apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "storage-be.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingress:
    - ports:
        - port: {{ .Values.containerPort }}
    - podSelector:
          matchLabels:
            app: dna-kong-gw-kong
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kong          
  podSelector:
    matchLabels:
      {{- include "storage-be.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress    
