apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.key }}
type: kubernetes.io/dockerconfigjson