apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.vault.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  vault.root.token: {{ .Values.app.vault.secret.rootToken | b64enc | quote }}
type: Opaque
