apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "code-server-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingress:
    - ports:
        - port: 7979
  podSelector:
    matchLabels:
      {{- include "code-server-backend.fullname" . | nindent 8 }}
