apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "code-server.name" . }}
  ingress:
    - from:
      - podSelector:
         matchLabels:
           app: dna-kong-gw-kong
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kong
        ports:
         - protocol: TCP
           port: {{ .Values.containerPort }}                 
  policyTypes:
    - Ingress
