apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "code-server.name" . }}
  ingress:
    - ports:
      - port: 8080
