spring:
  application:
    name: model-registry-service

dna:
  kube:
      config:
        namespace: ${KUBE_NAMESPACE:defaultNamespace}

server:
  port: 7373

#Cors Filter origin Domains  
allowedCorsOriginPatternUrl: ${CORS_ORIGIN_URL:http://*}





oidc:
  provider: ${OIDC_PROVIDER:OKTA}
  token:
    issuer: ${OIDC_ISSUER:xxxxx}
    introspection:
      url: ${OIDC_TOKEN_INTROSPECTION_URL:xxxxx}
    revocation:
      url: ${OIDC_TOKEN_REVOCATION_URL:xxxxx}
  userinfo:
    url: ${OIDC_USER_INFO_URL:xxxxx}
  disabled: ${OIDC_DISABLED:true}
  clientId: ${OIDC_CLIENT_ID:xxxxx}
  clientSecret: ${OIDC_CLIENT_SECRET:xxxxx}

jwt:
  secret:
    key: ${JWT_SECRET_KEY:oeRaYY7Wo24sDqKSX3IM9ASGmdGPmkTd9jo1QTy4b7P9Ze5_9hKolVX8xNrQDcNRfVEdTZNOuOyqEGhXEbdJI-ZQ19k_o9MI0y3eZN2lp9jow55FfXMiINEdt1XR85VipRLSOkT6kSpzs2x-jbLDiz9iFVzkd81YKxMgPA7VfZeQUm4n-mOmnWMaVX30zGFU4L3oPBctYKkl4dYfqYWqRNfrgPJVi5DGFjywgxx0ASEiJHtV72paI3fDR2XwlSkyhhmY-ICjCRmsJN4fX1pdoL8a18-aQrvyu4j0Os6dVPYIoPvvY0SAZtWYKHfM15g7A3HD4cVREf9cUsprCRK93w}
    byPassUrl: ${BYPASS_JWT_AUTHENTICATION:/api/login;/api/verifyLogin;/api/itsmmgame;/api/task-data;/api/warmup-data;/api/subscription/validate;/api/notification-preferences;}
    tokenExpiry: ${JWT_TOKEN_EXPIRY_TIME_IN_MIN:90}

drd:
  request-url: ${INTERNAL_USER_REQUEST_URL:xxxxx}
  certificate-file: ${INTERNAL_USER_CERT_FILE:xxxxx}
  certificate-pass: ${INTERNAL_USER_CERT_PASS:xxxxx}

task:
  delete:
    inactive-solutions-duration: ${INACTIVE_SOLUTION_DURATION_YRS:2} #years to check before deleting

jupyternotebook:
 baseuri: ${JUPYTER_NOTEBOOK_BASEURI:xxxxx}
 token: ${JUPYTER_NOTEBOOK_TOKEN:xxxxx}
 
storage:
  endpointurl: ${S3_EP_URL:xxxxxx}
  accesskey: ${S3_ACCESS_KEY:xxxxx}
  secretkey: ${S3_SECRET_KEY:xxxxx}
  bucketname: ${S3_BUCKET_NAME:xxxxx}
  maxParallelUploads: ${S3_MAX_PARALLEL_UPLOADTHREADS:20}
  minFileSize: ${S3_MIN_FILESIZE:1024}
  maxFileSize: ${S3_MAX_FILESIZE:5242880}


# Matomo Configuration
matomo:
  tracking: false
  siteId: ${MATOMO_SITE_ID:1}
  hostUrl: ${MATOMO_HOST_URL:xxxxx}

  
dataiku:
  apacCorpdir: ${APAC_CORPDIR:xxxxx}
  emeaCorpdir: ${EMEA_CORPDIR:xxxxx}
  projectsUriPath: ${DATAIKU_PROJECTS_URI_PATH:xxxxx}
  userRoleUriPath: ${DATAIKU_USER_ROLE_URI_PATH:xxxxx}
  projectPermissionUriPath: ${DATAIKU_PERMISSION_URI_PATH:xxxxx}
  production:
    uri: ${DATAIKU_PROD_URI:xxxxx}
    apiKey: ${DATAIKU_PROD_API_KEY:xxxxx}
    adminGroup: ${DATAIKU_PROD_ADMIN_GROUP:xxxxx}
  training:
    uri: ${DATAIKU_TRAINING_URI:xxxxx}
    apiKey: ${DATAIKU_TRAINING_API_KEY:xxxxx}
    adminGroup: ${DATAIKU_TRAINING_ADMIN_GROUP:xxxxx}    
  
avscan:
  uri: ${AVSCAN_URI:xxxxx}
  appid: ${AVSCAN_APP_ID:xxxxx}
  apiKey: ${AVSCAN_API_KEY:xxxxx} 

management.endpoints.web.exposure.include: loggers
management.endpoint.loggers.enabled: true

logging:
  service:
    environment: ${LOGGING_ENVIRONMENT:DEV}
    path: ${LOGGING_PATH:/var/log}
  level:
    com:
      daimler:
        data:
          application: INFO
          controller.ItsmmGameController: DEBUG
    org.springframework.boot.autoconfigure.logging: INFO
    com.daimler.data.controller.ItsmmGameController: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO
      hibernate:
        type:
          descriptor:
            sql: ERROR
      graphql:
        servlet: ERROR
