{{- if not .Values.vaultInjector.enable }}  
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "data-product-be.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range .Values.secret }}          
  {{ .key }}: {{ .value | b64enc | quote}}
{{- end }}  
{{- end }}