apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-registry.fullname" . }}
  labels:
    name: {{ include "model-registry.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "model-registry.name" . | nindent 8 }}
  template:
    metadata:
      labels:
        name: {{ include "model-registry.name" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
          runAsUser: 1000
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.envs }}            
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }} 