apiVersion: v1
kind: Secret
metadata:
  name: my-release-minio #{{ include "model-registry.name" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range .Values.secret }}          
  {{ .key }}: {{ .value | b64enc | quote}}
{{- end }}  
