apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dss-mfe.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingress:
    - from:
      - podSelector:
         matchLabels:
           app.kubernetes.io/name: traefikv2
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress
        ports:
         - port: 3000
           protocol: TCP
         - port: 7175
           protocol: TCP
  podSelector:
    matchLabels:
      {{- include "dss-mfe.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
