# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dna
imagePullSecret: 
  name: harbor-pull-secrets
  key: "docker-config"
ingress:
  enabled: true
  namespace: ingress
  host: "ingress-host"
  lbIP: ""
  
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""

configJs: |
    window["INJECTED_ENVIRONMENT"]={
      OIDC_DISABLED: false,
      DNA_APPNAME_HEADER: 'Sathish AAP',
      DNA_CONTACTUS_HTML: '<div><p>There could be many places where you may need our help, and we are happy to support you. <br /> Please add your communication channels links here</p></div>', 
      };
    
probes:
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 3

  readinessProbe:
    path: /
    port: 3000

appFrontend:
  replicaCount: 1
  image: dna/app-frontend
  ngnix:
    backend: http://dna-app-backend-service.dna.svc.cluster.local:80
    jupyServer: http://proxy-public:8000
    grafanaServer: http://i3-monitoring-grafana.i3-monitoring.svc.cluster.local:80
    avscanServer: http://clamav-rest-service.clamav.svc.cluster.local:8181
    avscanMgwServer: http://dna-microgateway.clamav.svc.cluster.local:80
    airflowServer: http://airflow.airflow.svc.cluster.local:8080
    naasServer: http://naas-backend-service.naas.svc.cluster.local:7272
    dashboard: http://dashboard-backend-service.dashboard.svc.cluster.local:7173
    storage: http://storage-be.storage.svc.cluster.local:80
