# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dna
imagePullSecret: 
  name: harbor-pull-secrets
  key: "docker-config"
ingress:
  enabled: true
  namespace: ingress
  host: "ingress-host"
  lbIP: ""
  
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""

configJs: |
    window["INJECTED_ENVIRONMENT"]={
      OIDC_DISABLED: "false",
      API_BASEURL: "api",
      STORAGE_API_BASEURL: "http://localhost:7175/storage/api",
      DNA_COMPANY_NAME: "Company_Name",
      DNA_APPNAME_HEADER: "DnA App",
      DNA_APPNAME_HOME: "Data and Analytics",
      DNA_CONTACTUS_HTML: "<div><p>There could be many places where you may need our help, and we are happy to support you. <br /> Please add your communication channels links here</p></div>",
      DNA_BRAND_LOGO_URL: "/images/branding/logo-brand.png",
      DNA_APP_LOGO_URL: "/images/branding/logo-app.png",
      OIDC_PROVIDER: "OKTA",
      CLIENT_IDS: "YOUR_CLIENT_ID",
      REDIRECT_URLS: "YOUR_OKTA_REDIRECT_URL",
      OAUTH2_AUTH_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/authorize",
      OAUTH2_LOGOUT_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/logout",
      OAUTH2_REVOKE_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/revoke",
      OAUTH2_TOKEN_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/token",
      ENABLE_INTERNAL_USER_INFO: "false",
      ENABLE_DATA_COMPLIANCE: "false",
      ENABLE_JUPYTER_WORKSPACE: "false",
      JUPYTER_NOTEBOOK_URL: "YOUR_NOTEBOOK_URL",
      JUPYTER_NOTEBOOK_OIDC_POPUP_URL: "YOUR_NOTEBOOK_AUTH_REDIRECT_URL",
      JUPYTER_NOTEBOOK_OIDC_POPUP_WAIT_TIME: "5000",
      ENABLE_DATAIKU_WORKSPACE: "false",
      DATAIKU_LIVE_APP_URL: "YOUR_DATAIKU_LIVE_URL",
      DATAIKU_TRAINING_APP_URL: "YOUR_DATAIKU_TRAINING_URL",
      DATAIKU_FERRET_URL: "YOUR_DATAIKU_FERRET_URL",
      ENABLE_MALWARE_SCAN_SERVICE: "true",
      MALWARE_SCAN_SWAGGER_UI_URL: "YOUR_MALWARE_SCAN_SWAGGER_UI_URL",
      ENABLE_MALWARE_SCAN_ONEAPI_INFO: "false",
      ENABLE_DATA_PIPELINE_SERVICE: "true",
      ENABLE_STORAGE_SERVICE: "true",
      CONTAINER_APP_URL: 'http://localhost:9090',
      STORAGE_MFE_APP_URL: "http://localhost:8083",
      ENABLE_REPORTS: "true",
      ENABLE_ML_PIPELINE_SERVICE: "true",
      ENABLE_NOTIFICATION: "true",
      ML_PIPELINE_URL: "YOUR_ML_PIPELINE_URL",
    };
    
probes:
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 3

  readinessProbe:
    path: /
    port: 3000

appFrontend:
  replicaCount: 1
  image: dna/app-frontend
  ngnix:
    backend: http://dna-app-backend-service.dna.svc.cluster.local:80
    jupyServer: http://proxy-public:8000
    grafanaServer: http://i3-monitoring-grafana.i3-monitoring.svc.cluster.local:80
    avscanServer: http://clamav-rest-service.clamav.svc.cluster.local:8181
    avscanMgwServer: http://dna-microgateway.clamav.svc.cluster.local:80
    airflowServer: http://airflow.airflow.svc.cluster.local:8080
    naasServer: http://naas-backend-service.naas.svc.cluster.local:7272
    dashboard: http://dashboard-backend-service.dashboard.svc.cluster.local:7173
    storage: http://storage-be.storage.svc.cluster.local:80
