apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  namespace: $(profile-name)
  annotations:
     serving.kubeflow.org/s3-endpoint: minio.storage.svc.cluster.local:9000 # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: USER_ID
  AWS_SECRET_ACCESS_KEY: PASSWORD

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-models
  namespace: $(profile-name)
secrets:
- name: s3creds